#ifndef __NODETYPES_H_
#define __NODETYPES_H_

enum node_type {
    PROGRAM,
    GLOBAL_LIST,
    GLOBAL,
    STATEMENT_LIST,
    PRINT_LIST,
    EXPRESSION_LIST,
    VARIABLE_LIST,
    ARGUMENT_LIST,
    PARAMETER_LIST,
    DECLARATION_LIST,
    FUNCTION,
    STATEMENT,
    BLOCK,
    ASSIGNMENT_STATEMENT,
    RETURN_STATEMENT,
    PRINT_STATEMENT,
    NULL_STATEMENT,
    IF_STATEMENT,
    WHILE_STATEMENT,
    EXPRESSION,
    RELATION,
    DECLARATION,
    PRINT_ITEM,
    IDENTIFIER_DATA,
    NUMBER_DATA,
    STRING_DATA
};

extern const char *node_t2s[26];

#endif // __NODETYPES_H_
